<?xml version="1.0" encoding="UTF-8"?>
<!--
    THIS XSLT IS AUTOGENERATED DO NOT EDIT
-->
<xsl:stylesheet xmlns:event="http://docs.rackspace.com/core/event"
                xmlns:atom="http://www.w3.org/2005/Atom"
                xmlns:httpx="http://openrepose.org/repose/httpx/v1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns="http://wadl.dev.java.net/2009/02"
                version="2.0">
   <xsl:output method="xml" indent="yes" encoding="UTF-8"/>

   <xsl:template name="main">
      <xsl:apply-templates mode="rm_priv"/>
   </xsl:template>

   <!--The productSchema-wadl.xsl call-template this one-->
   <xsl:template name="rmPrivAttrsTemplate">
      <xsl:param name="atomDoc" as="node()*"/>
      <xsl:apply-templates select="$atomDoc" mode="rm_priv"/>
   </xsl:template>

   <xsl:template match="@*|node()" mode="rm_priv">
      <xsl:copy>
         <xsl:apply-templates select="@*|node()" mode="rm_priv"/>
      </xsl:copy>
   </xsl:template>

    <!--For product: CloudServers -->
    <xsl:template xmlns:pf="http://docs.rackspace.com/event/servers/slice"
                 match="pf:product[@version='1']/@*[some $x in ('rootPassword', 'options', 'huddleId', 'serverId', 'customerId', 'flavorId', 'sliceType', 'privateIp') satisfies $x eq local-name(.)]"
                 mode="rm_priv"/>
   <xsl:template xmlns:pf="http://docs.rackspace.com/event/servers/hostserver"
                 match="pf:product[@version='1']/@*[some $x in ('coreID', 'huddleID', 'backstageURL') satisfies $x eq local-name(.)]"
                 mode="rm_priv"/>
   <xsl:template xmlns:pf="http://docs.rackspace.com/event/servers/hostserver"
                 match="pf:product[@version='2']/@*[some $x in ('coreID', 'huddleID', 'backstageURL') satisfies $x eq local-name(.)]"
                 mode="rm_priv"/>

    <!--For product: Widget -->
    <xsl:template xmlns:pf="http://docs.rackspace.com/usage/widget"
                 match="pf:product[@version='3']/@*[some $x in ('privateAttribute1', 'myAttribute', 'privateAttribute3') satisfies $x eq local-name(.)]"
                 mode="rm_priv"/>
   <xsl:template xmlns:pf="http://docs.rackspace.com/usage/widget"
                 match="pf:product[@version='3']/pf:metaData/@*[some $x in ('value') satisfies $x eq local-name(.)]"
                 mode="rm_priv"/>
   <xsl:template xmlns:pf="http://docs.rackspace.com/usage/widget"
                 match="pf:product[@version='3']/pf:mixPublicPrivateAttributes/@*[some $x in ('privateAttribute3') satisfies $x eq local-name(.)]"
                 mode="rm_priv"/>

   <!--For product: CloudIdentity-->
   <xsl:template xmlns:identity="http://docs.rackspace.com/event/identity/token"
                 match="event:event/@resourceId"
                 mode="rm_priv">
      <xsl:if test="not(parent::node()/identity:product)">
         <xsl:copy-of select="."/>
      </xsl:if>
   </xsl:template>
   <xsl:template xmlns:identity="http://docs.rackspace.com/event/identity/token"
                 match="atom:entry/atom:category[starts-with(@term, 'rid:')]"
                 mode="rm_priv">
      <xsl:if test="not(parent::node()/atom:content/event:event/identity:product)">
         <xsl:copy-of select="."/>
      </xsl:if>
   </xsl:template>
</xsl:stylesheet>
